version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: marvel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marvel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - .env.template
